version: "3"
services:
    app:
        image: react-app
        container_name: react-app
        restart: always
        build: ./react-app
        ports:
            - "3000:3000"
        working_dir: /app
        volumes:
            - ./react-app:/app
        entrypoint: ["npm", "start"]
        links:
            - api
        networks:
            - webappnetwork
    api:
        image: express-api
        container_name: express-api
        restart: always
        build: ./express-api
        ports:
            - "9000:9000"
        volumes:
            - ./express-api:/api
        networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge
